
package ua.voloshyn24.npv;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.voloshyn24.task.Task;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "npv_voloshyn24PortType", targetNamespace = "http://npv.voloshyn24.ua")
@XmlSeeAlso({
    com.voloshyn24.task.ObjectFactory.class,
    ua.voloshyn24.npv.ObjectFactory.class
})
public interface NpvVoloshyn24PortType {


    /**
     * 
     * @param tasks
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "VoloshynVolTaskGetter", action = "http://npv.voloshyn24.ua#npv_voloshyn24:VoloshynVolTaskGetter")
    @WebResult(targetNamespace = "http://npv.voloshyn24.ua")
    @RequestWrapper(localName = "VoloshynVolTaskGetter", targetNamespace = "http://npv.voloshyn24.ua", className = "ua.voloshyn24.npv.VoloshynVolTaskGetter")
    @ResponseWrapper(localName = "VoloshynVolTaskGetterResponse", targetNamespace = "http://npv.voloshyn24.ua", className = "ua.voloshyn24.npv.VoloshynVolTaskGetterResponse")
    public boolean voloshynVolTaskGetter(
        @WebParam(name = "tasks", targetNamespace = "http://npv.voloshyn24.ua")
        Task tasks);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Ping", action = "http://npv.voloshyn24.ua#npv_voloshyn24:Ping")
    @WebResult(targetNamespace = "http://npv.voloshyn24.ua")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://npv.voloshyn24.ua", className = "ua.voloshyn24.npv.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://npv.voloshyn24.ua", className = "ua.voloshyn24.npv.PingResponse")
    public boolean ping();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "JavaTest", action = "http://npv.voloshyn24.ua#npv_voloshyn24:JavaTest")
    @WebResult(targetNamespace = "http://npv.voloshyn24.ua")
    @RequestWrapper(localName = "JavaTest", targetNamespace = "http://npv.voloshyn24.ua", className = "ua.voloshyn24.npv.JavaTest")
    @ResponseWrapper(localName = "JavaTestResponse", targetNamespace = "http://npv.voloshyn24.ua", className = "ua.voloshyn24.npv.JavaTestResponse")
    public String javaTest();

}
